services:
  - type: web
    name: xfas-logistics-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: xfas_logistics
      - key: CORS_ORIGINS
        value: https://your-netlify-app.netlify.app,http://localhost:3000
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: PYTHON_VERSION
        value: 3.11.0
